#!/usr/bin/env bash
#The script that installs nginx on ubuntu server
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee -a /var.www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
