#!/usr/bin/env bash
# A script displays Best School x10, and then Hi on a new line after 9th time

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
