#!/usr/bin/env bash
# A script that display numbers 1~20 using while & case statements

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
