#!/usr/bin/env bash
# A script displays time from 12 hrs and 59min

hrs=0o
#displays hours from 0 to 12
while [ $hrs -le 12 ]
do
	echo "Hour : $hrs"
#displays minutes from 1 to 59
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((hrs++))
done
