#!/usr/bin/env bash
# Installs ufw and set up rules (Configures) FIREWALL

sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
